title: Data Science Portfolio
author: 
  name: Stephen Charles
  # email: stevemindoza@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Hi! I'm a Data Scientist with an interest in applying models to Astrophysics problems. My main projects can be found here, along with the journey to create them, documented in my Blog.
permalink: /:title/
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


linkedin_url: https://www.linkedin.com/in/stephen-charles-2b366020a/
github_url: https://github.com/sourestdeeds
#instagram_url: https://www.instagram.com/sourestdeeds/
#twitter_url: https://twitter.com/Sourestdeeds

  # generate social links in footer
  #social_links:
    # twitter: jekyllrb
    #github: sourestdeeds
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    #instagram: sourestdeeds
    #linkedin: stephen-charles-2b366020a
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
 


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
mathjax: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
